version: 2
updates:
  # Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: main
    reviewers:
      - spicelang/compiler-team
    assignees:
      - spicelang/compiler-team

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: .github/workflows/
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: main
    reviewers:
      - spicelang/compiler-team
    assignees:
      - spicelang/compiler-team

  # Python
  - package-ecosystem: pip
    directory: docs/
    schedule:
      interval: weekly # Weekly, because material for mkdocs updates quite often
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: main
    reviewers:
      - spicelang/documentation-team
    assignees:
      - spicelang/documentation-team