version: 2
updates:
  # CLI dependency updates
  - package-ecosystem: gomod
    directory: /cli
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: main
    reviewers:
      - chillibits/compiler-team
    assignees:
      - chillibits/compiler-team

  # VS Code integration
  - package-ecosystem: npm
    directory: /integration/vscode
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 20
    target-branch: develop
    reviewers:
    - chillibits/compiler-team
    assignees:
    - chillibits/compiler-team

  # Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    target-branch: main
    reviewers:
      - chillibits/compiler-team
    assignees:
      - chillibits/compiler-team