'compiler':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*'
          - 'test/**/*'
          - 'CMakeLists.txt'
          - 'Options.cmake'

'bootstrap':
  - changed-files:
      - any-glob-to-any-file:
          - 'src-bootstrap/**/*'

'std':
  - changed-files:
      - any-glob-to-any-file:
          - 'std/**/*'

'documentation':
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - 'media/specs/**/*'

'ci':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'