project_name: spice
builds:
  - dir: cli
    main: ./spice.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
      #- arm
      #- arm64
      - 386
    goarm:
      - 5
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=github-actions
dockers:
  - image_templates:
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/spicelang/spice:latest-amd64
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/spice:latest-amd64
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    goarch: amd64
    extra_files:
      - bin
      - std
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --build-arg=COMPILER_PATH=linux-amd64
      - --platform=linux/amd64
  - image_templates:
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - ghcr.io/spicelang/spice:latest-i386
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      - chillibits/spice:latest-i386
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    goarch: 386
    extra_files:
      - bin
      - std
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --build-arg=COMPILER_PATH=linux-386
      - --platform=linux/i386
  #- image_templates:
  #    - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
  #    - ghcr.io/spicelang/spice:latest-arm32v7
  #    - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
  #    - chillibits/spice:latest-arm32v7
  #  dockerfile: Dockerfile
  #  skip_push: auto
  #  use: buildx
  #  goarch: arm
  #  goarm: 7
  #  extra_files:
  #    - bin
  #    - std
  #  build_flag_templates:
  #    - --label=org.opencontainers.image.created={{.Date}}
  #    - --label=org.opencontainers.image.name={{.ProjectName}}
  #    - --label=org.opencontainers.image.revision={{.FullCommit}}
  #    - --label=org.opencontainers.image.version={{.Version}}
  #    - --label=org.opencontainers.image.source={{.GitURL}}
  #    - --build-arg=COMPILER_PATH=linux-armv7
  #    - --platform=linux/arm/v7
  #- image_templates:
  #    - ghcr.io/spicelang/spice:{{ .Version }}-arm64v8
  #    - ghcr.io/spicelang/spice:latest-arm64v8
  #    - chillibits/spice:{{ .Version }}-arm64v8
  #    - chillibits/spice:latest-arm64v8
  #  dockerfile: Dockerfile
  #  skip_push: auto
  #  use: buildx
  #  goarch: arm64
  #  extra_files:
  #    - bin
  #    - std
  #  build_flag_templates:
  #    - --label=org.opencontainers.image.created={{.Date}}
  #    - --label=org.opencontainers.image.name={{.ProjectName}}
  #    - --label=org.opencontainers.image.revision={{.FullCommit}}
  #    - --label=org.opencontainers.image.version={{.Version}}
  #    - --label=org.opencontainers.image.source={{.GitURL}}
  #    - --build-arg=COMPILER_PATH=linux-arm64
  #    - --platform=linux/arm64/v8
docker_manifests:
  - name_template: chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      #- chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      #- chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8
    skip_push: auto
  - name_template: chillibits/spice:latest
    image_templates:
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      #- chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      #- chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8
    skip_push: auto

  - name_template: ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      #- ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      #- ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8
    skip_push: auto
  - name_template: ghcr.io/spicelang/spice:latest
    image_templates:
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-i386
      #- ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm32v7
      #- ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8
    skip_push: auto
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - std
      - src: bin/spicec-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}/**
        dst: ./
        strip_parent: true
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
nfpms:
  - id: publish
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    maintainer: Marc Auberer <marc.auberer@chillibits.com>
    vendor: ChilliBits
    description: Spice programming language.
    homepage: https://www.spicelang.com
    license: MIT
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - build-essential
    contents:
      - src: bin/spicec-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}/*
        dst: /usr/lib/spice/
      - src: std/*
        dst: /usr/lib/spice/std/
      - src: bash_autocomplete.sh
        dst: /etc/bash_completion.d/spice
release:
  name_template: v{{ .Tag }}
  prerelease: auto
  footer: |
    ## What to do next?
    - [Install Spice](https://www.spicelang.com/install/linux/)
    - Visit [www.spicelang.com](https://www.spicelang.com) to test the new features
changelog:
  use: github
  filters:
    exclude:
    - Merge pull request
    - Merge branch
milestones:
  - close: true
    fail_on_error: false