project_name: spice
builds:
  - dir: cli
    goos:
      - linux
      #- windows
    goarch:
      - amd64
      #- arm
      #- arm64
      - 386
    #goarm:
    #  - 5
    #  #- 6 # Waiting for third party fix
    #  - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=github-actions
archives:
  - files:
      - LICENSE
      - bin/spicec-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}/* # Waiting for implementation: https://github.com/goreleaser/goreleaser/issues/1638
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - id: publish
    maintainer: Marc Auberer <marc.auberer@chillibits.com>
    description: Spice programming language.
    homepage: https://github.com/chillibits/spice
    license: MIT
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - build-essential
    contents:
      - src: bin/spicec-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}/*
        dst: /usr/lib/spice/
dockers:
  - image_templates:
      - ghcr.io/chillibits/spice:{{ .Version }}-amd64
      - ghcr.io/chillibits/spice:latest-amd64
      - chillibits/spice:{{ .Version }}-amd64
      - chillibits/spice:latest-amd64
    dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    extra_files:
      - bin
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --build-arg=COMPILER_PATH=linux-amd64
      - --platform=linux/amd64
  - image_templates:
      - ghcr.io/chillibits/spice:{{ .Version }}-i386
      - ghcr.io/chillibits/spice:latest-i386
      - chillibits/spice:{{ .Version }}-i386
      - chillibits/spice:latest-i386
    dockerfile: Dockerfile
    use: buildx
    goarch: 386
    extra_files:
      - bin
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --build-arg=COMPILER_PATH=linux-386
      - --platform=linux/i386
  #- image_templates:
  #    - ghcr.io/chillibits/spice:{{ .Version }}-arm32v7
  #    - ghcr.io/chillibits/spice:latest-arm32v7
  #    - chillibits/spice:{{ .Version }}-arm32v7
  #    - chillibits/spice:latest-arm32v7
  #  dockerfile: Dockerfile
  #  use: buildx
  #  goarch: arm
  #  goarm: 7
  #  extra_files:
  #    - bin
  #  build_flag_templates:
  #    - --label=org.opencontainers.image.created={{.Date}}
  #    - --label=org.opencontainers.image.name={{.ProjectName}}
  #    - --label=org.opencontainers.image.revision={{.FullCommit}}
  #    - --label=org.opencontainers.image.version={{.Version}}
  #    - --label=org.opencontainers.image.source={{.GitURL}}
  #    - --build-arg=COMPILER_PATH=linux-armv7
  #    - --platform=linux/arm/v7
  #- image_templates:
  #    - ghcr.io/chillibits/spice:{{ .Version }}-arm64v8
  #    - ghcr.io/chillibits/spice:latest-arm64v8
  #    - chillibits/spice:{{ .Version }}-arm64v8
  #    - chillibits/spice:latest-arm64v8
  #  dockerfile: Dockerfile
  #  use: buildx
  #  goarch: arm64
  #  extra_files:
  #    - bin
  #  build_flag_templates:
  #    - --label=org.opencontainers.image.created={{.Date}}
  #    - --label=org.opencontainers.image.name={{.ProjectName}}
  #    - --label=org.opencontainers.image.revision={{.FullCommit}}
  #    - --label=org.opencontainers.image.version={{.Version}}
  #    - --label=org.opencontainers.image.source={{.GitURL}}
  #    - --build-arg=COMPILER_PATH=linux-arm64
  #    - --platform=linux/arm64/v8
docker_manifests:
  - name_template: chillibits/spice:{{ .Version }}
    image_templates:
      - chillibits/spice:{{ .Version }}-amd64
      - chillibits/spice:{{ .Version }}-i386
      #- chillibits/spice:{{ .Version }}-arm32v7
      #- chillibits/spice:{{ .Version }}-arm64v8
  - name_template: chillibits/spice:latest
    image_templates:
      - chillibits/spice:{{ .Version }}-amd64
      - chillibits/spice:{{ .Version }}-i386
      #- chillibits/spice:{{ .Version }}-arm32v7
      #- chillibits/spice:{{ .Version }}-arm64v8
  - name_template: ghcr.io/chillibits/spice:{{ .Version }}
    image_templates:
      - ghcr.io/chillibits/spice:{{ .Version }}-amd64
      - ghcr.io/chillibits/spice:{{ .Version }}-i386
      #- ghcr.io/chillibits/spice:{{ .Version }}-arm32v7
      #- ghcr.io/chillibits/spice:{{ .Version }}-arm64v8
  - name_template: ghcr.io/chillibits/spice:latest
    image_templates:
      - ghcr.io/chillibits/spice:{{ .Version }}-amd64
      - ghcr.io/chillibits/spice:{{ .Version }}-i386
      #- ghcr.io/chillibits/spice:{{ .Version }}-arm32v7
      #- ghcr.io/chillibits/spice:{{ .Version }}-arm64v8
release:
  name_template: v{{ .Tag }}
  prerelease: auto
  footer: |
    ---
    
    __Visit [spicelang.com](https://www.spicelang.com) to test the new features!__
#announce:
#  twitter:
#    enabled: true
#    message_template: 'Spice {{ .Tag }} is now available! Check out the new features: www.spicelang.com!'
milestones:
  - close: true
    fail_on_error: false