site_name: Spice Programming Language
site_url: https://www.spicelang.com
site_description: The fast, powerful, self-contained and programmer oriented systems language Spice.
site_author: Marc Auberer
copyright: Made with ❤️ by Spice contributors, powered by <a href="https://www.chillibits.com" target="_blank">ChilliBits</a>.
repo_name: spicelang/spice
repo_url: https://github.com/spicelang/spice
edit_uri: edit/main/docs/docs/

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: static/avatar.png
  favicon: static/favicon-96x96.ico
  include_search_page: false
  search_index_only: true
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
    - content.action.edit
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme)"  # System preference
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/styles.css

plugins:
  - search:
      lang:
      - en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - offline

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spicelang/spice
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chillibits
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/chillibits/spice

nav:
  - Home: index.md
  - intro.md
  - Install:
    - install/windows.md
    - install/linux.md
    - install/docker.md
    - install/source.md
  - CLI Usage:
    - cli/build.md
    - cli/run.md
    - cli/test.md
    - cli/install.md
    - cli/uninstall.md
  - Tutorials:
    - how-to/oop.md
    - how-to/cli-parser.md
    - how-to/web-assembly.md
  - Documentation:
    - language/hello-world.md
    - language/main-function.md
    - language/builtins.md
    - language/primitive-types.md
    - language/builtin-types.md
    - language/casts.md
    - language/if-statements.md
    - language/while-loops.md
    - language/do-while-loops.md
    - language/for-loops.md
    - language/foreach-loops.md
    - language/procedures.md
    - language/functions.md
    - language/lambda-functions.md
    - language/modules.md
    - language/declaration-specifiers.md
    - language/attributes.md
    - language/arrays.md
    - language/pointers.md
    - language/references.md
    - language/enums.md
    - language/structs.md
    - language/methods.md
    - language/constructors-destructors.md
    - language/aliases.md
    - language/generics.md
    - language/threads.md
    - language/number-formats.md
    - language/operator-overloading.md
    - language/operator-precedence.md
  - contributing.md

markdown_extensions:
  - codehilite
  - meta
  - footnotes
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg