# C++ CI
name: C++ CI

on:
  push:
    paths:
      - compiler/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build:
    name: C++ CI
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ninja
        run: sudo apt-get install ninja-build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup Gcovr
        run: sudo pip install gcovr

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: /home/runner/work/spice/llvm
          key: llvm-13-0-1

      - name: Setup LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          cd ..
          git clone --depth  1 --branch llvmorg-13.0.1 https://github.com/llvm/llvm-project llvm
          mkdir ./llvm/build
          cd ./llvm/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS_RELEASE="-O2" -GNinja ../llvm
          cmake --build .

      - name: Download Libs
        run: |
          mkdir ./compiler/lib
          cd ./compiler/lib
          git clone --depth 1 --branch 4.9.3 https://github.com/antlr/antlr4.git
          mkdir json
          curl -SsL "https://github.com/nlohmann/json/releases/download/v3.10.5/json.hpp" --output json/json.hpp

      - name: Build Test target
        env:
          LLVM_DIR: /home/runner/work/spice/llvm/build/lib/cmake/llvm
        run: |
          mkdir ./compiler/bin
          cd ./compiler/bin
          cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -Wattributes ..
          cmake --build . --target Spice_test

      - name: Run Test target
        env:
          SPICE_STD_DIR: /home/runner/work/spice/spice/std
        run: |
          cd ./compiler/bin/test
          ./Spice_test "false"

      - name: Generate coverage report
        run: |
          cd ./compiler/bin
          sudo chmod +x coverage.sh
          sudo ./coverage.sh

      - name: Upload coverage report - coverage.spicelang.com
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./compiler/bin/coverage
          remoteDir: chillibits.com/spice/coverage

      - name: Upload coverage report - Codecov
        working-directory: ./compiler/bin
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}

# Currently not working because the data layout and the target triple is present in the ir test refs
#      - name: Check if test refs are up to date
#        env:
#          SPICE_STD_DIR: /home/runner/work/spice/spice/std
#        run: |
#          cd ./compiler/bin/test
#          ./Spice_test true
#          git status --porcelain
#          git diff --exit-code
