# C++ CI
name: C++ CI

on:
  push:
    paths:
      - compiler/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: /home/runner/work/spice/llvm
          key: llvm-13-0-0

      - name: Setup LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          cd ..
          git clone --depth  1 --branch llvmorg-13.0.0 https://github.com/llvm/llvm-project llvm
          mkdir ./llvm/build
          cd ./llvm/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS_RELEASE="-O2" -G "Unix Makefiles" ../llvm
          cmake --build .

      #- name: Prepare environment
      #  run: |
      #    shopt -s extglob
      #    rm -rf !("compiler")
      #    cp -fR ./compiler/* .
      #    rm -rf ./compiler

      - name: Download Libs
        run: |
          mkdir ./compiler/lib
          cd ./compiler/lib
          git clone --depth 1 https://github.com/antlr/antlr4.git

      - name: Build Test target
        env:
          LLVM_DIR: /home/runner/work/spice/llvm/build/lib/cmake/llvm
        run: |
          mkdir ./compiler/bin
          cd ./compiler/bin
          cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -DWITH_TESTS=ON -Wattributes ..
          cmake --build . --target Spice_test

      #- name: Build project
      #  uses: nicledomaS/cmake_build_action@v1.4
      #  env:
      #    LLVM_DIR: /home/runner/work/spice/llvm/build/lib/cmake/llvm
      #    SPICE_STD_DIR: /home/runner/work/spice/spice/std
      #  with:
      #    submodule_update: ON
      #    run_tests: ON
      #    cmake_args: -DWITH_TESTS=ON -Wattributes
      #    unit_test_build: -Dtest=ON

      - name: Run Test target
        env:
          SPICE_STD_DIR: /home/runner/work/spice/spice/std
        run: |
          cd ./compiler/bin/test
          ./Spice_test
