name: C++ CI

on:
  push:
    paths:
      - 'compiler/**'
  pull_request:
    branches: [ main, dev, feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: /home/runner/work/spice/llvm
          key: llvm-12-0-1

      - name: Setup LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          cd ..
          git clone https://github.com/llvm/llvm-project llvm
          mkdir ./llvm/build
          cd ./llvm/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS_RELEASE="-O2" -G "Unix Makefiles" ../llvm
          cmake --build .

      - name: Prepare environment
        run: |
          shopt -s extglob
          rm -rf !("compiler")
          cp -fR ./compiler/* .
          rm -rf ./compiler

      - name: Download Libs
        run: |
          mkdir -p ./lib
          cd ./lib
          git clone https://github.com/antlr/antlr4.git

      #- name: Build
      #  env:
      #    LLVM_DIR: /home/runner/work/spice/llvm/build/lib/cmake/llvm
      #  run: |
      #    mkdir bin
      #    cd bin
      #    cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -DWITH_TESTS=ON ../compiler
      #    cmake --build . --target Spice_run -- -j 6

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        env:
          LLVM_DIR: /home/runner/work/spice/llvm/build/lib/cmake/llvm
        with:
          submodule_update: ON
          run_tests: ON
          cmake_args: -DWITH_TESTS=ON
          unit_test_build: -Dtest=ON
