# C++ CI
name: C++ CI

on:
  push:
    paths:
      - compiler/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build:
    name: C++ CI
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: /home/runner/work/spice/llvm
          key: llvm-13-0-1

      - name: Setup LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          cd ..
          git clone --depth  1 --branch llvmorg-13.0.1 https://github.com/llvm/llvm-project llvm
          mkdir ./llvm/build
          cd ./llvm/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS_RELEASE="-O2" -G "Unix Makefiles" ../llvm
          cmake --build .

      - name: Download Libs
        run: |
          mkdir ./compiler/lib
          cd ./compiler/lib
          git clone --depth 1 --branch 4.9.3 https://github.com/antlr/antlr4.git
          mkdir json
          curl -SsL "https://github.com/nlohmann/json/releases/download/v3.10.5/json.hpp" --output json/json.hpp

      - name: Build Test target
        env:
          LLVM_DIR: /home/runner/work/spice/llvm/build/lib/cmake/llvm
        run: |
          mkdir ./compiler/bin
          cd ./compiler/bin
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_CXX_FLAGS_RELEASE="-O2" -Wattributes ..
          cmake --build . --target Spice_test

      - name: Run Test target
        env:
          SPICE_STD_DIR: /home/runner/work/spice/spice/std
        run: |
          cd ./compiler/bin/test
          ./Spice_test
