# Go CI
name: Go CI

on:
  push:
    paths:
      - cli/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build:
    name: Go CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - 1.17.x
          - 1.18.x
        os:
          - ubuntu-latest
          - windows-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Prepare environment
        run: |
          go version
          go mod vendor
          
      - name: Run build
        run: go build -x

      - name: Run vet
        run: go vet .
          
      - name: Run tests
        run: go test ./...

      - name: Install GoSec
        shell: bash
        run: curl -sfL https://raw.githubusercontent.com/securego/gosec/v2.10.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.10.0

      - name: Run security scan
        run: gosec -exclude=G204 ./...

      - name: Validate Goreleaser config
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check
