# Publish documentation
name: Publish documentation

on:
  push:
    branches:
      - main
      - docs/**
      - feature/**
      - fix/**
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  docs-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant
          pip install -r docs/requirements.txt

      - name: Build and deploy
        working-directory: docs
        run: mkdocs gh-deploy --force